/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package week3;

import java.util.ArrayList;
import java.util.List;
import junit.framework.TestCase;

/**
 *
 * @author Patrick
 */
public class GreedyMotifSearchTest extends TestCase {
    
    private String dna = "GATGGACCGGGCCATACATGGTGACACGCATCAGAAAGCTGTCCCCGTGCCTTATGCGCTGTCTGTTAGTACATCTCTCTCAATGGCCGTATTTTCAGAACAAGTATCACTTGGATCATCATCTACTCGACGGAGGGCGCGCAAGTGGGTATCTCG\n" +
"TAAAAAGGTATAAGGGAGTCATATCCGCAGTCCTAGTGACCTTTCCCGGCCCTAGCAGTGCTCCGATAGCCCATGGATGAGACGTAACTCGGCTACTGTTTGTGACTCAAGATAGTTGCCGTCGATATCTCGGATTCTGCTTATCGTGTTACGAGC\n" +
"AACCACGAGTACCTCTGTCGTGGTCCTTCACCAGGACTCGAAATTTGGCTCACGCCCAACGCCAAGATTACGTCGATCGTTCCTGTTGATATCTCGCCGCATATCAGGTTTATACTGATCGGCTCAGTGATTGTTAATCATCGGCGCGGGTTGTCA\n" +
"TGTCATGTGCGGATACAGTGGTGACACCAGGTCACCTCCGACCTAAAAGCGTTCAAGGTATGGCCCGAAGAGGTAGGTATCTCTTGTGCCCGCTGCTGCTATCACTCCCTGTGAGCCCCGACACGAATGTTAAACCAGTTTATATTCGCTCGTCAT\n" +
"AACCTAAACCCTTGCTTCCCACCATCCCTGCGAAGCAACCTTATCCGTAGTTCAGTCGCGCTGAACTCGGAAAGTGCGCTCACGAGATTCTAACTTACACTTGTTTAAGTACCACGTCCGGTGGATATCGCTGGCGTTGAAGGATAGTTCTGGTTA\n" +
"GTGCCCGATATGCCCGTCAGGGTTGAAGTCTGGGAAGTCGTTATCCCAAACGAAATACCCCGTTCGCAGGCGTGATGTATATCCTGATTAGTACCGCGTATAATATTAGTTTCGCACAGGAGCGTGCTTGTTTTGGGTCATGGATTGGGTACAGCA\n" +
"TAGTCTTCGAGGCATCTACCTGCGACCGAGCTTGCGATCCAAAAGCATACCCATGAAGTTTGCAAATCTTTCTTAGAGCTACAGGTAGATATCCCTGGGCCGGTAACTAGTAATATGTACAGTTTAGTTGTCCTGTACAATACTGATTGGAGTCAG\n" +
"AGGAGACGTGTTTGGTAGGCGCTCGACCCTTACCCCCCTATCTCGACTGGCATTGGACGTCCTCAGACTGGTGGATTTGACCTAGTGGTTATCACGCACATGGGAGAACCCGGTCAGAATACATCCTGTTACAGTCAGACGCCGGGTCATTCGCAA\n" +
"TGTGGGGATCGTCTGATTCATCGACGTCATGGAAACGGGGACGGGCCAGTGGTTATCCCATGCTGCCTTTTAGGAATTCTAGGAGGCGTTCCTAAATAGCTCGCCCGACGATATCCTACTTGATTGTGGCGGTATACCTTGCTGAACCTCGCAGTA\n" +
"CGCAGTGCACTAGTGGCTATCGCCTTTCTATCCCTGAGGCGTTTGCGTTATAAGATCACTCTGTCGGTGTGAAACCACTGAGTCACACTGACCGGTCGACTGGCCCGTCATATGCAAGTTGAAACGCTTACTGCCGGGTATCGCTCTAAGCTCGAC\n" +
"TACTCGTAACTTCAAAATCTCGTAGGGTCTGCAGAGTAAGAATCCCGGATACTTCAACATTATCGATTCGTCAAGACGTGCGGAGTGGATATCCCTTATTCCTATACGTCACAAGCCGCGGTCAAGTCGCTTACGCACGGTAGAGCGGGAAACCCT\n" +
"GCTCTAGTACGCCACAGTGCCAGTACATGACCTCACGAGCCGCCACTTACGTTGATATGTTATAAATCACTAGTTTCGTTGGTACAAACAATAAGTGAGAAGCAATGAGCAACTTATCTCATAAAAAGTGTGGTCGTTATCACACATGACATAAAC\n" +
"GAGACGGTCGTAGAAATTTGCGCTTGCTCGTATCTCAGTATCCTTCAAAGATTGAACCGGATCGCGGCGGCTAATATTGAAATCCTTAGACTTAACGTTGGTATCACTTTAGAATTTCTGACTTGAGGGTAGTGACTAGACAATCATGATGGAAGA\n" +
"GATCGGTGGCAGTTGAATTAAGACTAGTTATCCCCTGCTTACACTTTTTCCGCCCGGACACGTGTGACGGTAGTTGATATCTCTCAAGTATCCCGACTTCACGTACGATGCCACCCATCTCCGGCAAACACACTTCTATAATATCGTGGAGCCGAA\n" +
"GTAGGTATCACCAGAGTTCTCTCGGTATGTGGCGCTAAAACCTCTTAGAGTATGAAGGGTGAAGACCAAGCTCATACCACCCCTATATAGGGCTAATTAATTCCACATCCAGGCAAGATGTCACCCTACAGGTCGCTCACTTGTGGAGAACATCAC\n" +
"GTGGCTATCGCTGTGATCCGTCACACAAAATCAACTTTGTAGTATTTTGGGTAGTCGGGATAACGCGTGGTCTAAGGTGAGCTGCCTTTGATCCGTTGGGTGGCTACCTTGCAAGTTACCGGCTTGTCACTAGATATAACCGGAAGTCTCTGCAAA\n" +
"TGAGCAGACCCGACAAAGGCCATGACTTCAAAACCGGTTGTGCAGCGACAGGTACTTTAAGTACGGCACCATTAATATCGCTATACTTACGAGTTAGTGGGTATCTCATGCAAACAAACTGCTACTAGGAACTTAGACGAACTTACCAGGAGGATT\n" +
"AGTGATCTGAGCATAGTATACTGAGAACGTGTGTGTGACCCCTCCAGCGTCCCCGGCTACTGTTCCAGATCCTAACTAATTACTGCTAGCGATCTGGTCGATATCGCTACGGAACGAAGCCGTACAATCGCCCAGAAGCGGTTAGTCAAGGGCGTT\n" +
"CAAAATGGGAGTACTTCTCGTAGAATAATTCGTCTGTAATTCCTAGGTTCCATAGATAGGCCTCGATAGTGAAATTCCTTCATGCCCCGAGGTGGCGTTGATATCTCCTTTCTAAGCGGTACCCTTAAGAGTACTCGCGATGGGCTTATCCTCCTC\n" +
"GTTGGTATCACCCCCAATCCTCTTAGTTTACACTGTAAGATTAACGTCAGGGTGTTGTGGATGGCTTTTCTAATTTAGGTCCTCGGGATGCTCAGGTGTTACTATCGGACTGAGTGAATGTAAGTCCGGGTATCAGCCATGAAACCACTGGAGATC\n" +
"CCTCGGAAAACGTCGTAAGTGGTATCACAATCCACTAGTCACGGAGGGCGGTGAGTGTCTCGATGCTCAACCCCCAACCCTCAGATGAGGCTATCTGTAGGTATCACTTACGTCACTACGGGGAACAGCTCGCCTTAAGTGTAGGCTAGGTATATG\n" +
"GGCGGCTCCATCCGATGTGACGGATTTCATGAGGCACAAGCGCTTCACTCCCTATTTGGCTCGTGACAAAGTTCAACGGCTTTGCAGATATCCATGGTCGTTATCCCGGTGGTGAACCTACCGTCAAGTCTCTACAGTGCGCGAAGTGTCCCGGGC\n" +
"TACTAGTATAAGTTCCGAGCCAAATGGATGGCCCAGGCGCACTAGTGTTAGAAGGATTCGGGCTGTAGGTACATCAAGCTCGAATTTGTCCCACGTCATTCTGGGCCACCCGGACCACAGAAGACCTCTCTCTGTGCCGACGGTGTGGTTATCACG\n" +
"GTGGTTATCACCGGGATCGAATACAGATACGTCTGGTACATGCCTTGTCATTATTCATACGCCCCCTGGGCCAACAATCCTTTGTCAACCGCGGTCAAAAAGGTAACTAGGATCGGCTTGATCTCTAATTCCGGACTGTTCACCACGGGTCGACCG\n" +
"CATCACGCAATGCGAACGACTGAAGAAGGCAAGGACAGTTACGCAACCTATCATGCGTAGATCAAGGTAATCGGGACCGGTCTGGAATTTAGGAGTGTTGTTATCGCAACCTGCGATCATAACATCCTCTTATTGCCTATAAACCGACCCTGACCG";
    private int k = 12;
    private int t = 25;
    private GreedyMotifSearch greedyMotifSearch;
    
    public GreedyMotifSearchTest(String testName) {
        super(testName);
        greedyMotifSearch = new GreedyMotifSearch(dna, k, t);
    }
    
    @Override
    protected void setUp() throws Exception {
        super.setUp();
    }

//    public void testComputeGreedyMotifSearch() {
//        List<String> expected = new ArrayList<String>();
//        expected.add("AGTGGGTATCTC");
//        expected.add("TAAAAAGGTATA");
//        expected.add("AACCACGAGTAC");
//        expected.add("TGTCATGTGCGG");
//        expected.add("AACCTAAACCCT");
//        expected.add("AGTCGTTATCCC");
//        expected.add("AGTAATATGTAC");
//        expected.add("AGTGGTTATCAC");
//        expected.add("AGTGGTTATCCC");
//        expected.add("AGTGGCTATCGC");
//        expected.add("AGTGGATATCCC");
//        expected.add("AGTGAGAAGCAA");
//        expected.add("AGTGACTAGACA");
//        expected.add("TAAGACTAGTTA");
//        expected.add("TATGAAGGGTGA");
//        expected.add("AGTCGGGATAAC");
//        expected.add("AGTGGGTATCTC");
//        expected.add("AGCGGTTAGTCA");
//        expected.add("AGTGAAATTCCT");
//        expected.add("TGTGGATGGCTT");
//        expected.add("TGTAGGTATCAC");
//        expected.add("TGCAGATATCCA");
//        expected.add("TGTGGTTATCAC");
//        expected.add("TGTCATTATTCA");
//        expected.add("TGCGTAGATCAA");
//        
//        assertEquals(expected, greedyMotifSearch.computeGreedyMotifSearch());
//    }

//    public void testGenerateInitialMotif() {
//        List<String> expected = new ArrayList<String>();
//        expected.add("GGC");
//        expected.add("AAG");
//        expected.add("CAA");
//        expected.add("CAC");
//        expected.add("CAA");
//        
//        assertEquals(expected, greedyMotifSearch.generateInitialMotif(greedyMotifSearch.getDnaList()));
//    }
//    
//    public void testGenerateInitialConsensus() {
//        String expected = "CAA";
//        List<String> motif = greedyMotifSearch.generateInitialMotif(greedyMotifSearch.getDnaList());
//        assertEquals(expected, greedyMotifSearch.generateInitialConsensus(motif));
//    }
//    
//    public void testGenerateKMer() {
//        assertEquals(10, greedyMotifSearch.generateKMer(greedyMotifSearch.getDnaList().get(0)).size());
//    }
//    
//    public void testCompareToConsensusString() {
//        String consensus = "CAA";
//        String stringToCompare = "GAA";
//        String stringTwoToCompare = "GGG";
//        
//        assertEquals(1, greedyMotifSearch.compareToConsensusString(consensus, stringToCompare));
//        assertEquals(3, greedyMotifSearch.compareToConsensusString(consensus, stringTwoToCompare));
//    }
//    
//    public void testCalculateMotifScore() {
//        List<String> expected = new ArrayList<String>();
//        expected.add("AGTGGGTATCTC");
//        expected.add("TAAAAAGGTATA");
//        expected.add("AACCACGAGTAC");
//        expected.add("TGTCATGTGCGG");
//        expected.add("AACCTAAACCCT");
//        expected.add("AGTCGTTATCCC");
//        expected.add("AGTAATATGTAC");
//        expected.add("AGTGGTTATCAC");
//        expected.add("AGTGGTTATCCC");
//        expected.add("AGTGGCTATCGC");
//        expected.add("AGTGGATATCCC");
//        expected.add("AGTGAGAAGCAA");
//        expected.add("AGTGACTAGACA");
//        expected.add("TAAGACTAGTTA");
//        expected.add("TATGAAGGGTGA");
//        expected.add("AGTCGGGATAAC");
//        expected.add("AGTGGGTATCTC");
//        expected.add("AGCGGTTAGTCA");
//        expected.add("AGTGAAATTCCT");
//        expected.add("TGTGGATGGCTT");
//        expected.add("TGTAGGTATCAC");
//        expected.add("TGCAGATATCCA");
//        expected.add("TGTGGTTATCAC");
//        expected.add("TGTCATTATTCA");
//        expected.add("TGCGTAGATCAA");
//        String consensus = "GATGGTGACATC";
//        
//        assertEquals(195, greedyMotifSearch.calculateMotifScore(expected, consensus));
//    }
//    
//    public void testCreateProfile() {
//        List<String> profile = new ArrayList<String>();
//        profile.add("CAG");
//        profile.add("CAG");
//        profile.add("CAA");
//        String expected = "0.0 1.0 0.0 0.0/n1.0 0.0 0.0 0.0/n0.3333333333333333 0.0 0.6666666666666666 0.0/n";
//        String calculated = greedyMotifSearch.createProfile(profile);
//        assertEquals(expected, calculated);
//    }
    
    public void testCreateProfile() {
        List<String> profileList = new ArrayList<String>();
        profileList.add("ACCT");
        profileList.add("ATGT");
        profileList.add("ACGG");
        profileList.add("ACGA");
        
        greedyMotifSearch.createProfile(profileList);
    }
    
}
